### ISSUE TITLE
Missing compatibility identifiers for newer versions of Xcode

### ISSUE THREAD

**Issue by rpendleton** [rpendleton/xcode-canvas-color#3]
Xcode doesn't have an official plugin API and this plugin won't be loaded for new versions of Xcode. In order to fix this, the `Info.plist` of the plugin must be edited to include the latest `DVTPlugInCompatibilityUUID`.

Here are the steps to do this manually:
- In Finder, right click `Xcode.app` and click Show Package Contents
- Open `Contents/Info.plist`
- Copy the value of the `DVTPlugInCompatibilityUUID` key
- Add the value to the array called `DVTPlugInCompatibilityUUIDs` inside the plugin's `Info.plist`

**Comment by ryanp-me** [comment]
Xcode doesn't have an official plugin API and this plugin won't be loaded for new versions of Xcode. In order to fix this, the `Info.plist` of the plugin must be edited to include the latest `DVTPlugInCompatibilityUUID`.

Here are the steps to do this manually:

* In Finder, right click `Xcode.app` and click Show Package Contents
* Open `Contents/Info.plist`
* Copy the value of the `DVTPlugInCompatibilityUUID` key
* Add the value to the array called `DVTPlugInCompatibilityUUIDs` inside the plugin's `Info.plist`

**Comment by wdcurry** [comment]
Thanks @ryanp-me ! much appreciated.

**Comment by m-lombardo** [comment]
Many thanks, @ryanp-me

**Comment by rpendleton** [comment]
Glad you guys like it. I've added a script to the root of the repository that helps automate this process (and explained it in the README), so I'm going to go ahead and close this issue.
